# Generated by Django 4.1.7 on 2025-10-13 17:42

import app_home.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HrRunningNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('employee', 'Nhân viên'), ('collaborator', 'Cộng tác viên')], max_length=20, unique=True)),
                ('value', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HrUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='Mã nhân sự')),
                ('type', models.CharField(choices=[('employee', 'Nhân viên'), ('collaborator', 'Cộng tác viên')], default='employee', max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('contract', models.FileField(blank=True, null=True, upload_to=app_home.models.get_file_path)),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('contract_status', models.CharField(blank=True, choices=[('AC', 'Còn hiệu lực'), ('EX', 'Hết liệu lực')], max_length=2, null=True)),
                ('contract_type', models.CharField(blank=True, choices=[('OF', 'Chính thức'), ('IN', 'Thực tập sinh')], max_length=2, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('level', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_home.position')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_user_profile', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_profile', to='app_home.userprofile')),
            ],
        ),
    ]
