# Generated by Django 4.1.7 on 2025-10-16 12:09

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('MA', 'Nam'), ('FE', 'Nữ'), ('OT', 'Khác')], default='MA', max_length=20)),
                ('birth', models.DateField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_raw', models.CharField(blank=True, max_length=10, null=True)),
                ('birth_accuracy', models.CharField(blank=True, choices=[('year', 'Year only'), ('month', 'Month & Year'), ('day', 'Full Date')], max_length=10, null=True)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_date', models.DateField(blank=True, null=True)),
                ('main_status', models.CharField(choices=[('1', 'Khách chưa sử dụng dịch vụ'), ('2', 'Khách đang sử dụng dịch vụ'), ('3', 'Khách đã sử dụng dịch vụ')], default='1', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('carreer', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='customer_introducers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('incoming', 'Khách gọi tới'), ('outgoing', 'cuộc gọi đi')], max_length=100, null=True)),
                ('solidarity', models.CharField(blank=True, choices=[('glls', 'Gọi lại lần sau'), ('tb', 'Thuê bao'), ('knm', 'Không nghe máy'), ('cn', 'Cân nhắc'), ('dc', 'Đã chốt'), ('tc', 'Từ chối')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('level', models.PositiveIntegerField()),
                ('customer_type', models.CharField(blank=True, choices=[('1', 'Khách chưa sử dụng dịch vụ'), ('2', 'Khách đang sử dụng dịch vụ'), ('3', 'Khách đã sử dụng dịch vụ')], default=1, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('problem', models.TextField(blank=True, null=True)),
                ('encounter_pain', models.TextField(blank=True, null=True)),
                ('desire', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('color', colorfield.fields.ColorField(default='#0D6EFD', image_field=None, max_length=18, samples=None)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRunningNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='customer', max_length=20, unique=True)),
                ('value', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('source_link', models.CharField(blank=True, max_length=255, null=True)),
                ('format', models.CharField(blank=True, choices=[('direct', 'Trực tiếp'), ('indirect', 'Gián tiếp')], max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MA', 'Nam'), ('FE', 'Nữ'), ('OT', 'Khác')], max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('satification_level', models.CharField(blank=True, choices=[(1, 'Rất tệ'), (2, 'Tệ'), (3, 'Trung bình'), (4, 'Tốt'), (5, 'Xuất sắc')], max_length=10, null=True)),
                ('service_quality', models.CharField(blank=True, choices=[(1, 'Rất tệ'), (2, 'Tệ'), (3, 'Trung bình'), (4, 'Tốt'), (5, 'Xuất sắc')], max_length=10, null=True)),
                ('examination_quality', models.CharField(blank=True, choices=[(1, 'Rất tệ'), (2, 'Tệ'), (3, 'Trung bình'), (4, 'Tốt'), (5, 'Xuất sắc')], max_length=10, null=True)),
                ('serve_quality', models.CharField(blank=True, choices=[(1, 'Rất tệ'), (2, 'Tệ'), (3, 'Trung bình'), (4, 'Tốt'), (5, 'Xuất sắc')], max_length=10, null=True)),
                ('customercare_quality', models.CharField(blank=True, choices=[(1, 'Rất tệ'), (2, 'Tệ'), (3, 'Trung bình'), (4, 'Tốt'), (5, 'Xuất sắc')], max_length=10, null=True)),
                ('unsatify_note', models.TextField(blank=True, null=True)),
                ('suggest_note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('color', colorfield.fields.ColorField(default='#0D6EFD', image_field=None, max_length=18, samples=None)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('color', colorfield.fields.ColorField(default='#0D6EFD', image_field=None, max_length=18, samples=None)),
                ('note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ref_type', models.CharField(choices=[('customer', 'Khách hàng'), ('hr', 'CTV/HR'), ('actor', 'Actor thuộc LeadSource'), ('unknown', 'Khác/Không rõ')], default='unknown', max_length=20)),
                ('lookup_code', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='primary_referral', to='app_customer.customer')),
            ],
        ),
    ]
