# Generated by Django 4.1.7 on 2025-10-16 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_customer', '0001_initial'),
        ('app_product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_home', '0001_initial'),
        ('app_hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='ref_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_customers', to='app_home.leadsourceactor'),
        ),
        migrations.AddField(
            model_name='referral',
            name='ref_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_others', to='app_customer.customer'),
        ),
        migrations.AddField(
            model_name='referral',
            name='ref_hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_customers', to='app_hr.hruserprofile'),
        ),
        migrations.AddField(
            model_name='leadstatus',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='feedback_interested', to='app_product.service'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_source', to='app_home.leadsource'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerproblem',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_problems', to='app_customer.customer'),
        ),
        migrations.AddField(
            model_name='customerproblem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerlevel',
            name='lead_status',
            field=models.ManyToManyField(blank=True, to='app_customer.leadstatus'),
        ),
        migrations.AddField(
            model_name='customerlevel',
            name='treatment_state',
            field=models.ManyToManyField(blank=True, to='app_customer.treatmentstate'),
        ),
        migrations.AddField(
            model_name='customerlevel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customercare',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_care', to='app_customer.customer'),
        ),
        migrations.AddField(
            model_name='customercare',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer_introducers',
            name='commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_home.commission'),
        ),
        migrations.AddField(
            model_name='customer_introducers',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_customer.customer'),
        ),
        migrations.AddField(
            model_name='customer_introducers',
            name='introducer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_request',
            field=models.ManyToManyField(blank=True, to='app_customer.customerrequest'),
        ),
        migrations.AddField(
            model_name='customer',
            name='lead_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_customer.leadstatus'),
        ),
        migrations.AddField(
            model_name='customer',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='customer_interested', to='app_product.service'),
        ),
        migrations.AddField(
            model_name='customer',
            name='time_frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_home.timeframe'),
        ),
        migrations.AddField(
            model_name='customer',
            name='treatment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_customer.treatmentstate'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['ref_type'], name='app_custome_ref_typ_165aed_idx'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('ref_actor__isnull', True), ('ref_customer__isnull', False), ('ref_hr__isnull', True), ('ref_type', 'customer')), models.Q(('ref_actor__isnull', True), ('ref_customer__isnull', True), ('ref_hr__isnull', False), ('ref_type', 'hr')), models.Q(('ref_actor__isnull', False), ('ref_customer__isnull', True), ('ref_hr__isnull', True), ('ref_type', 'actor')), models.Q(('ref_actor__isnull', True), ('ref_customer__isnull', True), ('ref_hr__isnull', True), ('ref_type', 'unknown')), _connector='OR'), name='referral_exact_one_branch_or_unknown'),
        ),
    ]
