# Generated by Django 4.1.7 on 2025-10-16 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_home', '0001_initial'),
        ('app_hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsourceactor',
            name='hr_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leadsource_actors', to='app_hr.hruserprofile'),
        ),
        migrations.AddField(
            model_name='leadsourceactor',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='app_home.leadsource'),
        ),
        migrations.AddField(
            model_name='leadsource',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='functioncategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='floor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detailfunction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_home.functioncategory'),
        ),
        migrations.AddField(
            model_name='detailfunction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='user_profile_detail_function',
            unique_together={('user_profile', 'detail_function')},
        ),
        migrations.AddIndex(
            model_name='leadsourceactor',
            index=models.Index(fields=['source'], name='app_home_le_source__f65cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='leadsourceactor',
            index=models.Index(fields=['code'], name='app_home_le_code_ad78d0_idx'),
        ),
        migrations.AddIndex(
            model_name='leadsourceactor',
            index=models.Index(fields=['external_id'], name='app_home_le_externa_89b117_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leadsourceactor',
            unique_together={('source', 'name')},
        ),
    ]
