# Generated by Django 4.1.7 on 2025-10-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityDebtDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('method', models.CharField(choices=[('cash', 'Tiền mặt'), ('transfer', 'Chuyển khoản')], default='cash', max_length=25)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Chi tiết thanh toán vật tư',
                'verbose_name_plural': 'Chi tiết thanh toán vật tư',
            },
        ),
        migrations.CreateModel(
            name='ProductDebtDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('method', models.CharField(choices=[('cash', 'Tiền mặt'), ('transfer', 'Chuyển khoản')], default='cash', max_length=25)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Chi tiết thanh toán sản phẩm',
                'verbose_name_plural': 'Chi tiết thanh toán sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='SupplierFacilityDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Tổng nợ vật tư')),
            ],
            options={
                'verbose_name': 'Công nợ vật tư',
                'verbose_name_plural': 'Công nợ vật tư',
            },
        ),
        migrations.CreateModel(
            name='SupplierProductDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Tổng nợ sản phẩm')),
            ],
            options={
                'verbose_name': 'Công nợ sản phẩm',
                'verbose_name_plural': 'Công nợ sản phẩm',
            },
        ),
    ]
