# Generated by Django 4.1.7 on 2025-10-16 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproductdebt',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_product.supplier', verbose_name='Nhà cung cấp'),
        ),
        migrations.AddField(
            model_name='supplierproductdebt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierfacilitydebt',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_product.supplier', verbose_name='Nhà cung cấp'),
        ),
        migrations.AddField(
            model_name='supplierfacilitydebt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productdebtdetail',
            name='stock_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_product.stockin'),
        ),
        migrations.AddField(
            model_name='productdebtdetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facilitydebtdetail',
            name='stock_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_product.stockin'),
        ),
        migrations.AddField(
            model_name='facilitydebtdetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
